language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
sudo: false
cache:
- pip
install:
- pip install -r requirements-test.txt -e .
script: python setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: frankv
  password:
    secure: kn1LpHuzeWo22QrLRD7tw+awLV/IAtg0XQmGS4UriKCIk/IV4jIQ5mYknuw1HJ2RL2D04HqB+n6/5zwrJuOytkGMiRY6ZVco1B2Sfj4t/XMpM8NitI9oM4M95oilHZ9jpS7baM/5Lj2UyZQfa+JpYHPrZ1krIxnuUupw8sxAe9FW1ITEVQn/DPaz+Qbqpq4tlIKsG7crOw0fwwRYOjS6pFTZnxvzPvaJxUAXoygPbGjmhzwT30OHHOQLQw0lao7+41BM9C/iytfRERZ07A83LwSr9BdMQfS9V6plvehIaLlrNB6RPBypi7Tocr0C6+wTrmjHUOBXKmEZ1nSsBo5NuJwicbORSA9lSwSoJVq8naX5jFNQbralEW2w5Edsw5sfrJgTvzdoUzqS7/wSBf8SwtKoV79C5Y7kiXjvBXusml3+OMU59QRDQV0RjL2guAMm33CjLRFoxz3gU4VngLqBYeiOkfo4/uWK+Q4XrzUFPxJT8m36i+WR1g1vpKQOT+1VP0wz0kcHU7xekrEMfQ+lccGTvnv+jtkA7idC63LpcuGhSqRtYv10nt4GW+OynuKQrQ2NbRdPRHpYo9BX5nUHtCyohQjzg8nd1Mmu/+Qjb4ZIuzSp8BHcouSqufuuvLYVdwGCDBAFBnD1rL3RmhWhFmmDpPK6R4IrFsGR6JsP0Ig=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: frankV/flask-sendgrid
